### ISSUE TITLE
[FE]Initialize and set up repository

### ISSUE THREAD

**Issue by mimoham24** [reearth/reearth-cms#21]
# Description
Front-end development task of #5 

## Todos 
- [x] GraphQL codegen
- [x] Component layer architecture(maybe atoms, molecules, organisms and pages)
- [ ] Preview deploy for Netlify
- [x] #38
- [x] Setup style library(maybe `styled-component` or `emotion`?)
- [x] Setup global state management(maybe `jotai`)
- [x] Setup Renovate
- [x] Setup GraphQL sandbox
