### ISSUE TITLE
[BE]Initialize and set up repository 

### ISSUE THREAD

**Issue by mimoham24** [reearth/reearth-cms#22]
# Description
Back-end development task of #5  

## Todos
	- [ ] DB connection
	- [ ] gqlgen
	- [ ] otelgen
	- [ ] Authentication
		- [ ] Fetch public key from OIDC
		- [ ] verify JWT
	- [ ] Add light package for each layer
		- [ ] usecase
		- [ ] interactor
		- [ ] infrastructure
			- [ ] mongo
		- [ ] gateway
	- [ ] Create simple request which returns `Hello world`
	- [ ] Setup GraphQL Playground
