### ISSUE TITLE
[FE] Login 

### ISSUE THREAD

**Issue by issmail-basel** [reearth/reearth-cms#29]
# Description
Front-end development task of #1 

# Todos

- [x] Create auth directory
  - [x] Create auth hooks
    - [x] Auth0 wrapper
    - [x] Authentication require hook
  - [x] Create Auth0 provider with right configurations
  - [x] Create index page which wraps react elements
- [x] Add token to requests header in GQL provider
