### ISSUE TITLE
[BE] Authentication client

### ISSUE THREAD

**Issue by yk-eukarya** [reearth/reearth-cms#32]
# Description
Back-end development task of #1 

# Todos
- [ ] Investegate if we need to make a separate project (go package) 
- [ ] Investegate which of the following will be used
  - SSO (user shuold login once)
  - Auth twice one time for each domain
- [ ] Make 4 middlewares
  - [ ] 1. JWT validation middleware
  - [ ] 2. Inject the user depending on the 1st middleware
  - [ ] 3. Generate and inject the operator
  - [ ] 4. Validate the operator for authenticated endpoints
