### ISSUE TITLE
[BE]User queries and mutations

### ISSUE THREAD

**Issue by mimoham24** [reearth/reearth-cms#36]
# Description
Back-end development task of #31 

## Todos

- [ ] Query to fetch user info
- [ ] Mutation to edit user info
- [ ] Delete user ( for now, this is for E2E test )
